### ISSUE TITLE
CIS Updated to v2.1.0

### ISSUE THREAD

**Issue by bbaassssiiee** [rosshamilton1/cissec#1]
The benchmark was updated, any plans to update this repo too?

**Comment by rosshamilton1** [comment]
Hi there bbaassssiiee
Thanks for raising this, I'll try to find time to update the repo.  
tbh I'm very busy with work at the moment, so can't make any promises about timelines.
I'll try and look at it in the next few weeks.
Regards, 
Ross

**Comment by bbaassssiiee** [comment]
Why don't you join forces with us? https://github.com/MindPointGroup/RHEL7-CIS

**Comment by bbaassssiiee** [comment]
A few years have past, this repo is neglected.
